package com.relax.main.utils;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.UUID;


public class GameUtil {

    /*
     *  In practice, game ids will probably be generated by separate unique Id generator service
     *
     */
    public static String generateGameId(){
        return UUID.randomUUID().toString();
    }

    public static BigDecimal calculateAcrualPayout(int betAmount, BigDecimal payoutOn10){
        BigDecimal betTenMultiple = BigDecimal.valueOf(betAmount/10);
        BigDecimal payout = betTenMultiple.multiply(payoutOn10);
        BigDecimal roundedPayout = payout
                .setScale(2, RoundingMode.HALF_UP);

        return roundedPayout;
    }
}
