package com.relax.main.utils;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.UUID;


public class GameUtil {

    /*
     *  In practice, game ids will probably be generated by separate unique Id generator service
     *
     */
    public static String generateGameId(){
        return UUID.randomUUID().toString();
    }

    public static double calculateAcrualPayout(int betAmount,double payoutOn10){
        double betTenMultiple = (double) betAmount/10.00;
        double payout = betTenMultiple*payoutOn10;
        double roundedPayout = new BigDecimal(payout)
                .setScale(2, RoundingMode.HALF_UP)
                .doubleValue();

        return roundedPayout;
    }
}
