package com.relax.main.utils;
import java.util.UUID;


public class GameUtil {

    /*
     *  In practice, game ids will probably be generated by separate unique Id generator service
     *
     */
    public static String generateGameId(){
        return UUID.randomUUID().toString();
    }
}
